version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4000:${APP_PORT}"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://${TYPEORM_BACKEND_USERNAME}:${TYPEORM_BACKEND_PASSWORD}@postgres:5432/${TYPEORM_BACKEND_DATABASE}
    depends_on:
      - postgres
  postgres:
    env_file:
      - .env 
    image: postgres:14.9
    environment:
      POSTGRES_USER: ${TYPEORM_BACKEND_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_BACKEND_PASSWORD}
      POSTGRES_DB: ${TYPEORM_BACKEND_DATABASE}
    ports:
      - 5432:5432
